#!/Usr/bin/env ruby
puts "The students of Villains Academy"
puts "--------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Bowser"
puts "Ganondorf"
puts "Manus"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
puts " "
